version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run:
          name: Clean Project
          command: ./gradlew clean
      - run:
          name: Build Project
          command: ./gradlew build