version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Java Version
          command: java -version
      - run:
          name: Clean
          command: ./gradlew clean
      - run:
          name: Build
          command: ./gradlew build -x test -x check
      - run:
          name: Test
          command: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results/
      - store_artifacts:
          path: build/reports/tests/test/