version: 2.1

jobs:
  build:
    steps:
      - checkout
      - run:
          name: Clean Project
          command: ./gradlew clean
      - run:
          name: Build Project
          command: ./gradlw build



